name: Build

on:
  push:
    branches:
      - main
      - develop

  pull_request:

jobs:
  build:
    runs-on: windows-latest

    env:
      DOTNET_VERSION: "9.0.x"

    steps:
      - name: Checkout application
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet build --configuration Release --no-restore

      # Uncomment once tests exist
      #
      # - name: Run tests
      #   run: dotnet test --configuration Release --no-build